version: "3.8"

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3-bookworm
    env_file:
      - .env
    environment:
      - DISPLAY=$IP:0
    volumes:
      - ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../input:/input:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
